### ISSUE TITLE
source-map name and "file" parameter are incorrect if multiple less files are compiled

### ISSUE THREAD

**Issue by ai212983** [Deraen/less4clj#16]
I have a number of .less files, all imported in `site.main.less` file.
`lein less4j once` properly creates `site.css` and map file named `site.main.css.map` (not `site.css.map`).
It works (because same file name is specified in `site.css`), but doesn't feel quite right and some tools fails to associate them properly.

Real bug is there's target file specified inside `site.main.css.map`: 

> "file":"devcards.main.css",

There's no such file, of course.

I am not sure if it is a [Less4j](https://github.com/SomMeri/less4j) or [less4clj](https://github.com/Deraen/less4clj) issue, but I believe "file" should point to `site.css` and it would be nice that name of the map file was matching css file (i.e. `site.css.map`, not `site.main.css.map`).

**Comment by Deraen** [comment]
Fixed in 0.7.4.
