### ISSUE TITLE
Less files cannot be imported from other directories that are configured in :source-paths

### ISSUE THREAD

**Issue by Juholei** [Deraen/less4clj#18]
We used older version, 0.3.2, in our project, and had two different directories configured in our project.clj under :source-paths (basically like this {:less {:source-paths ["src/less" "less"]}}). In these directories it was possible to import files from the other source path and vice versa with no problems. After updating to the newest version this no longer works, error given is "The file file.less does not exist." This can be fixed by using a relative path to the file in the import statement but then it seems it does not matter if the other directory even is configured in source-paths.

So is it a bug with the newest version that the directories configured as source-paths do not see files in the other directories in source-paths or was the old functionality we relied on with the old version not meant to be?

**Comment by Deraen** [comment]
Fixed in 0.7.3.
