### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by Deraen** [Deraen/less4clj#4]
Atleast https://github.com/Deraen/less4clj/blob/master/src/less4clj/core.clj#L21 looks suspicious

**Comment by chrispoulsen** [comment]
I had to change the following to get things running on windows: 
````
diff --git a/src/less4clj/core.clj b/src/less4clj/core.clj
index 5591ee6..1ec62fe 100644
--- a/src/less4clj/core.clj
+++ b/src/less4clj/core.clj
@@ -23,7 +23,7 @@
     x))

 (defn join-url [a b]
-  (str (.resolve (URI. (if (.endsWith a "/") a (str a "/"))) (URI. b))))
+  (str (.resolve (.toURI ( clojure.java.io/file (if (.endsWith a "/") a (str a "/")))) (.toURI (clojure.java.io/file b)))))

 (defn find-resource [url]
   (if url
````

**Comment by Deraen** [comment]
I got tests running on Windows on AppVeyor CI: https://ci.appveyor.com/project/Deraen/less4clj/build/4

**Comment by Deraen** [comment]
I fixed one pboem and at leasts tests are now passing on CI. Please open new issues if there are still problems.
