### ISSUE TITLE
If target-dir option is not given NPE is thrown

### ISSUE THREAD

**Issue by Deraen** [Deraen/less4clj#6]

**Comment by Leonidas-from-XIV** [comment]
Yep, I ran into the same issue. At first I thought this is a dependency issue, but it goes away if I specify `:target-dir` in `:less` in `project.clj`.

**Comment by Deraen** [comment]
Fixed by https://github.com/Deraen/less4clj/commit/ac5029111d951119dc904183032015650a0bf82d
