### ISSUE TITLE
less4clj fails when there are spaces in the directory (uri)

### ISSUE THREAD

**Issue by ikitommi** [Deraen/less4clj#8]
It seems to fail with `less4clj.core/join-url` with the `java.net.URI` constructor, not accepting whitespace.

```
java.net.URISyntaxException: Illegal character in path at index 66: /home/jenkins/.boot/cache/tmp/opt/jenkins/.jenkins/workspace/Kikka - Develop/fab/-reftg1/css/
```

**Comment by bjconlan** [comment]
I believe that this is also causing problems for windows as I'm getting a very similar error (due to the path being incorrect) when I've set the lein project to use `:source-paths ["resources/less"]`I see:

```
Compiling {less}... accounts.main.less
java.net.URISyntaxException: Illegal character in path at index 9: resources\less/
...
```
